spring.application.name=14-SESSION-BACKEND-CRUD


spring.h2.console.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/likelion_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=alstlsdnjs1229
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update